In [6]:
import  numpy as np

arr1 = np.array([1,2,3,4,5])
list1 = [1,2,3,4,5]
print(arr1)
print(list1)

print(type(arr1))
print(type(list1))

[1 2 3 4 5]
[1, 2, 3, 4, 5]
<class 'numpy.ndarray'>
<class 'list'>


In [9]:
arr2 = np.array([[1,2],[2,3]])
print(arr2)
print(arr2.ndim)

[[1 2]
 [2 3]]
2


In [7]:
arr1 = np.array([1,2,3])
print(arr1)
print(arr1.ndim)


[1 2 3]
1


In [11]:
arr3 = np.array([[[1,2],[3,4],[5,6]]])
print(arr3)
print(arr3.ndim)

[[[1 2]
  [3 4]
  [5 6]]]
3


Practice day-1 (2/10)

In [13]:
arr = np.array([10,20,30,40,50])
print(arr)
print(arr.dtype)

[10 20 30 40 50]
int64


In [15]:
arr = np.array([5, 10, 15, 20, 25])
print("first element",arr[0])
print("last element",arr[-1])

print("elemnt at index",arr[2])


first element 5
last element 25
elemnt at index 15


In [17]:
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[1:4])

print(arr[::2])

[20 30 40]
[10 30 50]


In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)  


print(arr.ndim)
print(arr.shape)


print(arr[1:2,1:2])
print(arr[0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
[[5]]
0


Numpy - array attributes
